In [55]:
import pandas as pd

In [56]:
df_test = pd.read_csv('healthkathon_afterpreprocessing.csv')
df_test = df_test.sort_values(by='id', ascending=True)
df_test

,Unnamed: 0,id,id_peserta,dati2,typefaskes,usia,jenkel,pisat,jenispel,politujuan,...,tgldatang_year,tgldatang_month,tgldatang_day,tgldatang_hour,tgldatang_minute,tglpulang_year,tglpulang_month,tglpulang_day,tglpulang_hour,tglpulang_minute
3836911,11328419,1,4294260,1,25,34,0,1.0,1,0,...,2017,12,31,17,0,2018,1,3,17,0
8709704,4732811,2,1173029,1,25,9,1,4.0,2,179,...,2018,1,1,17,0,2018,1,1,17,0
11145743,3615269,3,6714367,1,25,37,0,1.0,2,159,...,2018,1,2,17,0,2018,1,2,17,0
10569794,3211011,4,1168460,1,25,44,1,3.0,1,0,...,2018,1,2,17,0,2018,1,4,17,0
9314296,5489306,5,1014590,1,25,15,1,4.0,1,0,...,2018,1,2,17,0,2018,1,6,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7166528,474584,11426953,980654,386,3,51,0,1.0,2,142,...,2020,12,11,17,0,2020,12,11,17,0
10073321,3379363,11426954,2176337,386,3,31,1,3.0,2,162,...,2020,12,14,17,0,2020,12,14,17,0
5225816,9920496,11426955,2228160,386,3,54,1,3.0,2,162,...,2020,12,14,17,0,2020,12,14,17,0
1162789,7941957,11426956,2192754,386,3,48,0,1.0,2,159,...,2020,12,18,17,0,2020,12,18,17,0
8128522,1405002,11426957,2212167,386,3,47,1,3.0,2,162,...,2020,12,2,17,0,2020,12,2,17,0

In [38]:
X_test = df_test.drop(columns=['Unnamed: 0', 'label'])
X_test

,id,id_peserta,dati2,typefaskes,usia,jenkel,pisat,jenispel,politujuan,diagfktp,...,tgldatang_year,tgldatang_month,tgldatang_day,tgldatang_hour,tgldatang_minute,tglpulang_year,tglpulang_month,tglpulang_day,tglpulang_hour,tglpulang_minute
0,5205817,6069898,51,1,28,0,1.0,2,121,11462,...,2019,7,17,17,0,2019,7,17,17,0
1,478976,5386227,46,2,11,0,4.0,1,0,640,...,2018,7,16,17,0,2018,7,17,17,0
2,1368497,6320192,112,2,48,0,1.0,2,167,2924,...,2019,2,26,17,0,2019,2,26,17,0
3,11397717,5507444,364,2,30,1,3.0,2,121,1686,...,2018,6,27,17,0,2018,6,27,17,0
4,7244025,3340328,120,2,41,1,1.0,2,167,2768,...,2018,10,3,17,0,2018,10,3,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11401877,2096276,1630386,130,23,70,1,3.0,1,0,14698,...,2020,11,24,17,0,2020,11,28,17,0
11401878,7525084,1630386,130,1,67,1,3.0,2,167,2742,...,2018,4,16,17,0,2018,4,16,17,0
11401879,2092640,1630386,130,23,70,1,3.0,1,0,81,...,2020,6,14,17,0,2020,6,17,17,0
11401880,2075609,1630390,129,24,50,0,1.0,2,162,5071,...,2019,7,24,17,0,2019,7,24,17,0
11401881,102794,8527876,12,25,0,1,4.0,1,0,10515,...,2020,12,29,17,0,2020,12,31,17,0

In [57]:
y_test = df_test['label']
y_test

3836911     0
8709704     0
11145743    0
10569794    0
9314296     0
           ..
7166528     0
10073321    0
5225816     0
1162789     0
8128522     0
Name: label, Length: 11401882, dtype: int64

In [34]:
df_train = pd.read_csv('trainset_randomoversampling2.csv')

In [2]:
df_train = pd.read_csv('trainset_SMOTE.csv')

In [35]:
df_train

,Unnamed: 0,id,id_peserta,dati2,typefaskes,usia,jenkel,pisat,jenispel,politujuan,...,tgldatang_month,tgldatang_day,tgldatang_hour,tgldatang_minute,tglpulang_year,tglpulang_month,tglpulang_day,tglpulang_hour,tglpulang_minute,label
0,0,5205817,6069898,51,1,28,0,1.0,2,121,...,7,17,17,0,2019,7,17,17,0,1
1,1,478976,5386227,46,2,11,0,4.0,1,0,...,7,16,17,0,2018,7,17,17,0,1
2,2,1368497,6320192,112,2,48,0,1.0,2,167,...,2,26,17,0,2019,2,26,17,0,1
3,3,11397717,5507444,364,2,30,1,3.0,2,121,...,6,27,17,0,2018,6,27,17,0,1
4,4,7244025,3340328,120,2,41,1,1.0,2,167,...,10,3,17,0,2018,10,3,17,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1886217,1886217,6038004,7147605,501,2,23,0,4.0,2,167,...,1,14,17,0,2019,1,14,17,0,1
1886218,1886218,4356274,3396560,223,24,21,0,4.0,2,121,...,2,27,17,0,2018,2,27,17,0,1
1886219,1886219,691550,5280237,69,17,41,0,1.0,2,179,...,2,9,17,0,2020,2,9,17,0,1
1886220,1886220,140291,5336730,13,2,26,1,3.0,2,183,...,6,18,17,0,2019,6,18,17,0,1
1886221,1886221,3397598,7514120,184,24,0,0,4.0,1,0,...,11,1,17,0,2018,11,3,17,0,1

In [36]:
df_X = df_train.drop(columns=['label', 'Unnamed: 0'])
df_X

,id,id_peserta,dati2,typefaskes,usia,jenkel,pisat,jenispel,politujuan,diagfktp,...,tgldatang_year,tgldatang_month,tgldatang_day,tgldatang_hour,tgldatang_minute,tglpulang_year,tglpulang_month,tglpulang_day,tglpulang_hour,tglpulang_minute
0,5205817,6069898,51,1,28,0,1.0,2,121,11462,...,2019,7,17,17,0,2019,7,17,17,0
1,478976,5386227,46,2,11,0,4.0,1,0,640,...,2018,7,16,17,0,2018,7,17,17,0
2,1368497,6320192,112,2,48,0,1.0,2,167,2924,...,2019,2,26,17,0,2019,2,26,17,0
3,11397717,5507444,364,2,30,1,3.0,2,121,1686,...,2018,6,27,17,0,2018,6,27,17,0
4,7244025,3340328,120,2,41,1,1.0,2,167,2768,...,2018,10,3,17,0,2018,10,3,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1886217,6038004,7147605,501,2,23,0,4.0,2,167,2742,...,2019,1,14,17,0,2019,1,14,17,0
1886218,4356274,3396560,223,24,21,0,4.0,2,121,5147,...,2018,2,27,17,0,2018,2,27,17,0
1886219,691550,5280237,69,17,41,0,1.0,2,179,3592,...,2020,2,9,17,0,2020,2,9,17,0
1886220,140291,5336730,13,2,26,1,3.0,2,183,10286,...,2019,6,18,17,0,2019,6,18,17,0
1886221,3397598,7514120,184,24,0,0,4.0,1,0,10426,...,2018,11,1,17,0,2018,11,3,17,0

In [37]:
df_y = df_train['label']
df_y

0          1
1          1
2          1
3          1
4          1
          ..
1886217    1
1886218    1
1886219    1
1886220    1
1886221    1
Name: label, Length: 1886222, dtype: int64

In [9]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [19]:
nb.fit(df_X, df_y)

GaussianNB()

In [10]:
ypred_nb = nb.predict(X_test)

NotFittedError: This GaussianNB instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [21]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred_nb))
print(confusion_matrix(y_test, ypred_nb))

              precision    recall  f1-score   support

           0       0.99      0.47      0.64  11244993
           1       0.02      0.58      0.03    156889

    accuracy                           0.47  11401882
   macro avg       0.50      0.53      0.33  11401882
weighted avg       0.97      0.47      0.63  11401882

[[5323457 5921536]
 [  65357   91532]]

In [17]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=3)

In [18]:
model.fit(df_X, df_y)

KNeighborsClassifier(n_neighbors=3)

In [19]:
ypred_knn = model.predict(X_test)

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred_knn))
print(confusion_matrix(y_test, ypred_knn))

In [36]:
from sklearn.ensemble import AdaBoostClassifier

ada=AdaBoostClassifier()

In [37]:
ada.fit(df_X, df_y)

AdaBoostClassifier()

In [38]:
ypred_ada = ada.predict(X_test)

In [39]:
print(classification_report(y_test, ypred_ada))
print(confusion_matrix(y_test, ypred_ada))

              precision    recall  f1-score   support

           0       0.99      0.87      0.93  11244993
           1       0.06      0.58      0.11    156889

    accuracy                           0.87  11401882
   macro avg       0.53      0.73      0.52  11401882
weighted avg       0.98      0.87      0.92  11401882

[[9825786 1419207]
 [  65782   91107]]

In [10]:
from xgboost import XGBClassifier
sgb = XGBClassifier()

In [11]:
sgb.fit(df_X, df_y)

C:\Users\akbar\anaconda3\envs\gpu2\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[06:40:13] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [12]:
ypred_sgb = sgb.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred_sgb))
print(confusion_matrix(y_test, ypred_sgb))

              precision    recall  f1-score   support

           0       1.00      0.89      0.94  11244993
           1       0.09      0.80      0.16    156889

    accuracy                           0.89  11401882
   macro avg       0.54      0.85      0.55  11401882
weighted avg       0.98      0.89      0.93  11401882

[[10003226  1241767]
 [   31264   125625]]

In [45]:
df_sub2 = pd.DataFrame()

In [47]:
df_sub2['id'] = df_test['id']

In [48]:
df_sub2['label'] = ypred_sgb

In [49]:
df_sub2

                id  label
0          5205817      1
1           478976      0
2          1368497      1
3         11397717      1
4          7244025      0
...            ...    ...
11401877   2096276      0
11401878   7525084      1
11401879   2092640      0
11401880   2075609      0
11401881    102794      0

[11401882 rows x 2 columns]

In [50]:
df_sub2.to_csv('answer2.csv',index=False)

In [15]:
from sklearn.tree import DecisionTreeClassifier

dtc=DecisionTreeClassifier()
dtc.fit(df_X, df_y)

DecisionTreeClassifier()

In [16]:
ypred_dtc = dtc.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred_dtc))
print(confusion_matrix(y_test, ypred_dtc))

              precision    recall  f1-score   support

           0       1.00      0.91      0.96  11244993
           1       0.14      1.00      0.25    156889

    accuracy                           0.92  11401882
   macro avg       0.57      0.96      0.60  11401882
weighted avg       0.99      0.92      0.95  11401882

[[10279581   965412]
 [       0   156889]]

In [40]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [41]:
rf.fit(df_X, df_y)

RandomForestClassifier()

In [42]:
ypred_rf = rf.predict(X_test)

In [58]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(classification_report(y_test, ypred_rf))
print(confusion_matrix(y_test, ypred_rf))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98  11244993
           1       0.01      0.02      0.01    156889

    accuracy                           0.97  11401882
   macro avg       0.50      0.50      0.50  11401882
weighted avg       0.97      0.97      0.97  11401882

[[11027803   217190]
 [  154155     2734]]

In [44]:
df_sub1 = pd.DataFrame()

In [45]:
df_sub1['id'] = df_test['id']

In [46]:
df_sub1['label'] = ypred_rf

In [51]:
df_sub1 = df_sub1.sort_values(by='id', ascending=True)

In [52]:
df_sub1

                id  label
3836911          1      0
8709704          2      0
11145743         3      0
10569794         4      0
9314296          5      0
...            ...    ...
7166528   11426953      0
10073321  11426954      0
5225816   11426955      0
1162789   11426956      0
8128522   11426957      0

[11401882 rows x 2 columns]

In [53]:
df_sub1.to_csv('answer3.csv',index=False)

In [23]:
df_X.corr()

,id,id_peserta,dati2,typefaskes,usia,jenkel,pisat,jenispel,politujuan,diagfktp,...,kdsp,kdsr,kdsi,kdsd,tgldatang_year,tgldatang_month,tgldatang_day,tglpulang_year,tglpulang_month,tglpulang_day
id,1.000000,-0.018882,0.525412,-0.434575,0.011783,-0.027502,-0.000404,-0.023820,-0.040820,0.000245,...,-0.025321,-0.035033,-0.042460,-0.048167,-0.008198,-0.007321,-0.004500,-0.007040,-0.007086,-0.004517
id_peserta,-0.018882,1.000000,0.026664,0.055071,-0.456208,-0.049714,0.261442,-0.181172,-0.207471,0.149203,...,-0.002678,0.027993,0.035952,0.040761,0.092099,0.041480,0.005778,0.092694,0.041518,0.008346
dati2,0.525412,0.026664,1.000000,-0.070803,0.018382,0.005920,-0.009803,0.022335,0.020197,0.027540,...,0.047603,0.022485,0.027960,0.036425,0.024880,0.009407,-0.001634,0.024933,0.009564,-0.002512
typefaskes,-0.434575,0.055071,-0.070803,1.000000,0.014459,0.027686,-0.009134,0.004935,0.028002,0.000098,...,0.046666,0.052539,0.062272,0.079406,0.029669,0.020970,-0.001317,0.029101,0.020930,-0.000292
usia,0.011783,-0.456208,0.018382,0.014459,1.000000,0.039588,-0.593942,0.194070,0.250172,-0.183173,...,0.076180,0.000286,-0.011745,0.021283,-0.007581,-0.010025,-0.004161,-0.007943,-0.010359,-0.006075
jenkel,-0.027502,-0.049714,0.005920,0.027686,0.039588,1.000000,0.167238,-0.005493,0.003810,0.000218,...,-0.000775,0.002239,-0.000994,0.007735,-0.005256,0.000905,-0.000653,-0.005710,0.000613,-0.000978
pisat,-0.000404,0.261442,-0.009803,-0.009134,-0.593942,0.167238,1.000000,-0.141284,-0.174944,0.106987,...,-0.033748,0.001890,0.006565,-0.010451,0.000558,0.006809,0.001239,0.000908,0.007350,0.002496
jenispel,-0.023820,-0.181172,0.022335,0.004935,0.194070,-0.005493,-0.141284,1.000000,0.930162,-0.123124,...,0.035386,-0.032504,-0.024280,-0.005840,-0.008451,-0.012114,-0.003260,-0.014032,-0.013953,-0.014884
politujuan,-0.040820,-0.207471,0.020197,0.028002,0.250172,0.003810,-0.174944,0.930162,1.000000,-0.113807,...,0.043886,-0.034774,-0.028368,0.001720,-0.026985,-0.020237,-0.003824,-0.032157,-0.021952,-0.014617
diagfktp,0.000245,0.149203,0.027540,0.000098,-0.183173,0.000218,0.106987,-0.123124,-0.113807,1.000000,...,-0.045674,-0.005994,-0.016478,0.017484,-0.020385,-0.001858,0.004299,-0.020360,-0.002098,0.004160
biaya,0.036961,0.040762,-0.026531,-0.037339,-0.032990,-0.019279,0.024111,-0.423076,-0.399965,0.039338,...,0.118185,0.086308,0.009620,-0.019342,0.017984,0.005417,-0.001019,0.023047,0.008179,0.008129
jenispulang,0.029939,0.005703,-0.003894,-0.040971,0.033168,-0.014104,-0.013334,-0.092499,-0.091393,0.016045,...,-0.010466,-0.000333,-0.000374,0.000779,0.017918,0.003957,0.001534,0.018626,0.004011,0.001550
cbg,-0.016750,0.067858,0.007737,0.019356,-0.090193,0.049391,0.044512,0.304762,0.275243,0.192178,...,-0.096475,-0.012429,-0.014615,0.015478,0.012245,0.006004,0.003337,0.009197,0.005126,-0.001922
kelasrawat,0.011953,-0.045079,0.010202,-0.058909,0.082024,0.003641,-0.027358,0.548358,0.510048,-0.071994,...,0.015874,-0.025826,-0.018081,-0.011366,-0.001650,-0.004295,-0.002073,-0.003953,-0.005662,-0.007469
kdsa,-0.007784,0.014054,0.013368,0.036640,-0.004285,-0.010991,0.007820,-0.042517,-0.042201,-0.029910,...,0.098936,0.450025,0.511907,0.480173,0.074714,0.095750,0.005350,0.083319,0.100981,0.005575
kdsp,-0.025321,-0.002678,0.047603,0.046666,0.076180,-0.000775,-0.033748,0.035386,0.043886,-0.045674,...,1.000000,0.182657,0.194725,0.184699,0.027320,0.043978,-0.000173,0.027079,0.044032,-0.001327
kdsr,-0.035033,0.027993,0.022485,0.052539,0.000286,0.002239,0.001890,-0.032504,-0.034774,-0.005994,...,0.182657,1.000000,0.870618,0.815651,0.142368,0.166622,0.009281,0.142386,0.167581,0.005045
kdsi,-0.042460,0.035952,0.027960,0.062272,-0.011745,-0.000994,0.006565,-0.024280,-0.028368,-0.016478,...,0.194725,0.870618,1.000000,0.926829,0.161148,0.189671,0.010642,0.161104,0.190285,0.006279
kdsd,-0.048167,0.040761,0.036425,0.079406,0.021283,0.007735,-0.010451,-0.005840,0.001720,0.017484,...,0.184699,0.815651,0.926829,1.000000,0.155480,0.178486,0.008576,0.155533,0.178983,0.003833
tgldatang_year,-0.008198,0.092099,0.024880,0.029669,-0.007581,-0.005256,0.000558,-0.008451,-0.026985,-0.020385,...,0.027320,0.142368,0.161148,0.155480,1.000000,-0.073938,-0.010705,0.997331,-0.071016,-0.004412
tgldatang_month,-0.007321,0.041480,0.009407,0.020970,-0.010025,0.000905,0.006809,-0.012114,-0.020237,-0.001858,...,0.043978,0.166622,0.189671,0.178486,-0.073938,1.000000,0.001217,-0.067575,0.983773,0.001870
tgldatang_day,-0.004500,0.005778,-0.001634,-0.001317,-0.004161,-0.000653,0.001239,-0.003260,-0.003824,0.004299,...,-0.000173,0.009281,0.010642,0.008576,-0.010705,0.001217,1.000000,-0.005603,0.002066,0.823116
tglpulang_year,-0.007040,0.092694,0.024933,0.029101,-0.007943,-0.005710,0.000908,-0.014032,-0.032157,-0.020360,...,0.027079,0.142386,0.161104,0.155533,0.997331,-0.067575,-0.005603,1.000000,-0.076661,-0.009052
tglpulang_month,-0.007086,0.041518,0.009564,0.020930,-0.010359,0.000613,0.007350,-0.013953,-0.021952,-0.002098,...,0.044032,0.167581,0.190285,0.178983,-0.071016,0.983773,0.002066,-0.076661,1.000000,0.000166
tglpulang_day,-0.004517,0.008346,-0.002512,-0.000292,-0.006075,-0.000978,0.002496,-0.014884,-0.014617,0.004160,...,-0.001327,0.005045,0.006279,0.003833,-0.004412,0.001870,0.823116,-0.009052,0.000166,1.000000